# Generated by Django 2.2 on 2019-06-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('drive', models.IntegerField(verbose_name='drive')),
                ('hp', models.IntegerField(verbose_name='hp')),
                ('rent_per_hour', models.IntegerField(verbose_name='rent per hour')),
                ('brand_name', models.CharField(choices=[('John Deere', 'John Deere'), ('Tafe', 'Tafe'), ('Escorts', 'Escorts'), ('Swaraj', 'Swaraj'), ('Mahindra', 'Mahindra'), ('Sonalika', 'Sonalika'), ('Trakstar', 'Trakstar'), ('Kubota', 'Kubota')], default='1', max_length=30, verbose_name='brand')),
                ('model_name', models.CharField(max_length=30, verbose_name='model')),
                ('note', models.TextField(blank=True, verbose_name='note')),
            ],
        ),
    ]
